// Original Spanish summaries, teaching fixtures and SQLite reference solutions.
// LeetCode links identify the source exercise, not the author of these solutions.
const literal = (v) =>
  v === null
    ? 'NULL'
    : typeof v === 'number'
      ? String(v)
      : `'${v.replaceAll("'", "''")}'`;
const table = (name, schema, rows) => ({
  name,
  setup: `CREATE TABLE ${name} (${schema});\n${rows.length ? `INSERT INTO ${name} VALUES ${rows.map((r) => '(' + r.map(literal).join(',') + ')').join(',')};` : ''}`,
});
const p = (
  id,
  title,
  slug,
  difficulty,
  topic,
  description,
  tables,
  query,
  expected,
  hint,
) => ({
  id,
  title,
  slug,
  difficulty,
  topic,
  description,
  tables: tables.map((t) => t.name),
  setup: tables.map((t) => t.setup).join('\n'),
  query,
  expected,
  hint,
});

const exercises = [
  p(
    595,
    'Países grandes',
    'big-countries',
    'Easy',
    'SELECT · OR',
    'Devuelve name, population y area de los países con **al menos 3.000.000 km²** o **25.000.000 de habitantes**.',
    [
      table(
        'World',
        'name TEXT PRIMARY KEY, continent TEXT, area INTEGER, population INTEGER, gdp INTEGER',
        [
          ['Aster', 'Europe', 3000000, 8000000, 50000000],
          ['Boreal', 'Asia', 500000, 25000000, 70000000],
          ['Celia', 'Europe', 100000, 900000, 4000000],
        ],
      ),
    ],
    'SELECT name, population, area\nFROM World\nWHERE area >= 3000000 OR population >= 25000000;',
    [
      ['Aster', 8000000, 3000000],
      ['Boreal', 25000000, 500000],
    ],
    'OR incluye los países que cumplen cualquiera de los dos umbrales.',
  ),
  p(
    1148,
    'Autores que leen sus artículos',
    'article-views-i',
    'Easy',
    'DISTINCT',
    'Encuentra los autores que han visto alguno de sus propios artículos. Devuelve su identificador como **id**, sin repetirlo y en orden ascendente.',
    [
      table(
        'Views',
        'article_id INTEGER, author_id INTEGER, viewer_id INTEGER, view_date TEXT',
        [
          [1, 4, 4, '2020-01-01'],
          [1, 4, 4, '2020-01-02'],
          [2, 2, 2, '2020-01-01'],
          [3, 7, 9, '2020-01-01'],
        ],
      ),
    ],
    'SELECT DISTINCT author_id AS id\nFROM Views\nWHERE author_id = viewer_id\nORDER BY id;',
    [[2], [4]],
    'Primero compara autor y lector; DISTINCT elimina las lecturas repetidas.',
  ),
  p(
    1683,
    'Tuits demasiado largos',
    'invalid-tweets',
    'Easy',
    'LENGTH',
    'Devuelve tweet_id de los tuits cuyo contenido tiene **más de 15 caracteres**. Exactamente 15 sí es válido.',
    [
      table('Tweets', 'tweet_id INTEGER PRIMARY KEY, content TEXT', [
        [1, 'Hola SQL'],
        [2, '123456789012345'],
        [3, '1234567890123456'],
      ]),
    ],
    'SELECT tweet_id\nFROM Tweets\nWHERE LENGTH(content) > 15;',
    [[3]],
    'LENGTH cuenta caracteres en SQLite.',
  ),
  p(
    1068,
    'Análisis de ventas I',
    'product-sales-analysis-i',
    'Easy',
    'INNER JOIN',
    'Para cada venta, muestra **product_name, year y price**. El precio es por unidad; no se solicita el importe total.',
    [
      table(
        'Sales',
        'sale_id INTEGER, product_id INTEGER, year INTEGER, quantity INTEGER, price INTEGER',
        [
          [1, 10, 2020, 2, 100],
          [2, 10, 2021, 3, 90],
          [3, 20, 2021, 1, 200],
        ],
      ),
      table('Product', 'product_id INTEGER PRIMARY KEY, product_name TEXT', [
        [10, 'Teclado'],
        [20, 'Monitor'],
        [30, 'Ratón'],
      ]),
    ],
    'SELECT p.product_name, s.year, s.price\nFROM Sales AS s\nJOIN Product AS p ON p.product_id = s.product_id;',
    [
      ['Teclado', 2020, 100],
      ['Teclado', 2021, 90],
      ['Monitor', 2021, 200],
    ],
    'Une las ventas con su producto usando product_id.',
  ),
  p(
    197,
    'Temperaturas en aumento',
    'rising-temperature',
    'Easy',
    'SELF JOIN · fechas',
    'Devuelve el **id** de los días cuya temperatura supera la del día natural anterior. Una fecha sin día anterior registrado no cuenta.',
    [
      table(
        'Weather',
        'id INTEGER PRIMARY KEY, recordDate TEXT, temperature INTEGER',
        [
          [1, '2020-01-01', 10],
          [2, '2020-01-02', 15],
          [3, '2020-01-03', 12],
          [4, '2020-01-05', 30],
        ],
      ),
    ],
    "SELECT today.id\nFROM Weather AS today\nJOIN Weather AS yesterday\n  ON today.recordDate = date(yesterday.recordDate, '+1 day')\nWHERE today.temperature > yesterday.temperature;",
    [[2]],
    'Compara fechas, no identificadores consecutivos.',
  ),
  p(
    1661,
    'Tiempo medio por máquina',
    'average-time-of-process-per-machine',
    'Easy',
    'JOIN · AVG',
    'Cada proceso tiene un evento start y otro end. Calcula **processing_time** medio por machine_id, redondeado a **tres decimales**.',
    [
      table(
        'Activity',
        'machine_id INTEGER, process_id INTEGER, activity_type TEXT, timestamp REAL',
        [
          [0, 1, 'start', 1],
          [0, 1, 'end', 2.5],
          [0, 2, 'start', 3],
          [0, 2, 'end', 5.5],
          [1, 1, 'start', 0.2],
          [1, 1, 'end', 1.4],
        ],
      ),
    ],
    "SELECT s.machine_id, ROUND(AVG(e.timestamp - s.timestamp), 3) AS processing_time\nFROM Activity AS s\nJOIN Activity AS e ON s.machine_id = e.machine_id AND s.process_id = e.process_id\nWHERE s.activity_type = 'start' AND e.activity_type = 'end'\nGROUP BY s.machine_id;",
    [
      [0, 2],
      [1, 1.2],
    ],
    'Empareja el inicio y el final de cada proceso antes de promediar.',
  ),
  p(
    577,
    'Bonificaciones de empleados',
    'employee-bonus',
    'Easy',
    'LEFT JOIN · NULL',
    'Muestra **name y bonus** de quienes tienen una bonificación inferior a 1000 o no tienen bonificación registrada.',
    [
      table(
        'Employee',
        'empId INTEGER PRIMARY KEY, name TEXT, supervisor INTEGER, salary INTEGER',
        [
          [1, 'Luz', null, 5000],
          [2, 'Pau', 1, 3000],
          [3, 'Sol', 1, 4000],
        ],
      ),
      table('Bonus', 'empId INTEGER PRIMARY KEY, bonus INTEGER', [
        [2, 500],
        [3, 1000],
      ]),
    ],
    'SELECT e.name, b.bonus\nFROM Employee AS e\nLEFT JOIN Bonus AS b ON b.empId = e.empId\nWHERE b.bonus < 1000 OR b.bonus IS NULL;',
    [
      ['Luz', null],
      ['Pau', 500],
    ],
    'Conserva los empleados sin correspondencia mediante LEFT JOIN.',
  ),
  p(
    1280,
    'Estudiantes y exámenes',
    'students-and-examinations',
    'Easy',
    'CROSS JOIN · COUNT',
    'Para cada estudiante y asignatura muestra **student_id, student_name, subject_name y attended_exams**, incluyendo los ceros. Ordena por estudiante y asignatura.',
    [
      table('Students', 'student_id INTEGER PRIMARY KEY, student_name TEXT', [
        [1, 'Eva'],
        [2, 'Leo'],
      ]),
      table('Subjects', 'subject_name TEXT PRIMARY KEY', [['Math'], ['SQL']]),
      table('Examinations', 'student_id INTEGER, subject_name TEXT', [
        [1, 'SQL'],
        [1, 'SQL'],
        [2, 'Math'],
      ]),
    ],
    'SELECT s.student_id, s.student_name, u.subject_name, COUNT(e.student_id) AS attended_exams\nFROM Students AS s\nCROSS JOIN Subjects AS u\nLEFT JOIN Examinations AS e ON e.student_id = s.student_id AND e.subject_name = u.subject_name\nGROUP BY s.student_id, s.student_name, u.subject_name\nORDER BY s.student_id, u.subject_name;',
    [
      [1, 'Eva', 'Math', 0],
      [1, 'Eva', 'SQL', 2],
      [2, 'Leo', 'Math', 1],
      [2, 'Leo', 'SQL', 0],
    ],
    'CROSS JOIN crea todas las parejas; COUNT de una columna ignora los NULL del LEFT JOIN.',
  ),
  p(
    1934,
    'Tasa de confirmación',
    'confirmation-rate',
    'Medium',
    'LEFT JOIN · CASE',
    'Para cada usuario registrado calcula **confirmation_rate**: solicitudes confirmed entre solicitudes totales, con dos decimales. Sin solicitudes, la tasa es 0.',
    [
      table('Signups', 'user_id INTEGER PRIMARY KEY, time_stamp TEXT', [
        [1, '2020-01-01'],
        [2, '2020-01-01'],
        [3, '2020-01-01'],
      ]),
      table('Confirmations', 'user_id INTEGER, time_stamp TEXT, action TEXT', [
        [1, '2020-01-02', 'confirmed'],
        [1, '2020-01-03', 'timeout'],
        [2, '2020-01-02', 'confirmed'],
      ]),
    ],
    "SELECT s.user_id, ROUND(AVG(CASE WHEN c.action = 'confirmed' THEN 1.0 ELSE 0.0 END), 2) AS confirmation_rate\nFROM Signups AS s\nLEFT JOIN Confirmations AS c ON c.user_id = s.user_id\nGROUP BY s.user_id;",
    [
      [1, 0.5],
      [2, 1],
      [3, 0],
    ],
    'Transforma cada confirmación en 1 y los demás casos en 0.',
  ),
  p(
    620,
    'Películas que no aburren',
    'not-boring-movies',
    'Easy',
    'WHERE · ORDER BY',
    'Devuelve todas las columnas de las películas con **id impar** y descripción distinta de boring. Ordena por rating descendente.',
    [
      table(
        'Cinema',
        'id INTEGER PRIMARY KEY, movie TEXT, description TEXT, rating REAL',
        [
          [1, 'Norte', 'great', 8.2],
          [2, 'Sur', 'great', 9],
          [3, 'Este', 'boring', 7],
          [5, 'Oeste', 'fun', 9.1],
        ],
      ),
    ],
    "SELECT id, movie, description, rating\nFROM Cinema\nWHERE id % 2 = 1 AND description <> 'boring'\nORDER BY rating DESC;",
    [
      [5, 'Oeste', 'fun', 9.1],
      [1, 'Norte', 'great', 8.2],
    ],
    'El resto de dividir un entero impar entre 2 es 1.',
  ),
  p(
    1251,
    'Precio medio de venta',
    'average-selling-price',
    'Easy',
    'JOIN · media ponderada',
    'Calcula **average_price** por producto ponderando cada precio por las unidades vendidas en su intervalo de fechas, incluidos ambos extremos. Redondea a dos decimales; sin ventas, devuelve 0.',
    [
      table(
        'Prices',
        'product_id INTEGER, start_date TEXT, end_date TEXT, price INTEGER',
        [
          [1, '2020-01-01', '2020-01-10', 10],
          [1, '2020-01-11', '2020-01-31', 20],
          [2, '2020-01-01', '2020-01-31', 30],
        ],
      ),
      table(
        'UnitsSold',
        'product_id INTEGER, purchase_date TEXT, units INTEGER',
        [
          [1, '2020-01-10', 2],
          [1, '2020-01-11', 1],
        ],
      ),
    ],
    'SELECT p.product_id, COALESCE(ROUND(1.0 * SUM(p.price * u.units) / SUM(u.units), 2), 0) AS average_price\nFROM Prices AS p\nLEFT JOIN UnitsSold AS u ON u.product_id = p.product_id AND u.purchase_date BETWEEN p.start_date AND p.end_date\nGROUP BY p.product_id;',
    [
      [1, 13.33],
      [2, 0],
    ],
    'Divide el importe total entre las unidades, no entre el número de ventas.',
  ),
  p(
    1075,
    'Experiencia media por proyecto',
    'project-employees-i',
    'Easy',
    'JOIN · AVG',
    'Devuelve **project_id y average_years**, la experiencia media de sus empleados redondeada a dos decimales.',
    [
      table('Project', 'project_id INTEGER, employee_id INTEGER', [
        [1, 1],
        [1, 2],
        [2, 2],
        [2, 3],
      ]),
      table(
        'Employee',
        'employee_id INTEGER PRIMARY KEY, name TEXT, experience_years INTEGER',
        [
          [1, 'Ada', 3],
          [2, 'Ben', 2],
          [3, 'Cora', 6],
        ],
      ),
    ],
    'SELECT p.project_id, ROUND(AVG(e.experience_years), 2) AS average_years\nFROM Project AS p\nJOIN Employee AS e ON e.employee_id = p.employee_id\nGROUP BY p.project_id;',
    [
      [1, 2.5],
      [2, 4],
    ],
    'Agrupa las asignaciones por proyecto después de recuperar la experiencia.',
  ),
  p(
    1633,
    'Porcentaje de usuarios en concursos',
    'percentage-of-users-attended-a-contest',
    'Easy',
    'CTE · porcentaje',
    'Devuelve contest_id y **percentage** de usuarios inscritos respecto a todos los usuarios, con dos decimales. Ordena por porcentaje descendente y contest_id ascendente.',
    [
      table('Users', 'user_id INTEGER PRIMARY KEY, user_name TEXT', [
        [1, 'Ada'],
        [2, 'Ben'],
        [3, 'Cora'],
      ]),
      table('Register', 'contest_id INTEGER, user_id INTEGER', [
        [10, 1],
        [10, 2],
        [20, 2],
        [20, 3],
        [30, 1],
      ]),
    ],
    'WITH total AS (SELECT COUNT(*) AS users_count FROM Users)\nSELECT r.contest_id, ROUND(100.0 * COUNT(*) / t.users_count, 2) AS percentage\nFROM Register AS r CROSS JOIN total AS t\nGROUP BY r.contest_id, t.users_count\nORDER BY percentage DESC, r.contest_id;',
    [
      [10, 66.67],
      [20, 66.67],
      [30, 33.33],
    ],
    'Calcula el total de usuarios una sola vez; 100.0 evita la división entera.',
  ),
  p(
    1211,
    'Calidad de las consultas',
    'queries-quality-and-percentage',
    'Easy',
    'AVG · CASE',
    'Por query_name calcula **quality**, la media de rating dividido por position, y **poor_query_percentage**, el porcentaje con rating menor que 3. Redondea ambos a dos decimales.',
    [
      table(
        'Queries',
        'query_name TEXT, result TEXT, position INTEGER, rating INTEGER',
        [
          ['SQL', 'A', 1, 5],
          ['SQL', 'B', 2, 2],
          ['Web', 'C', 2, 4],
          ['Web', 'D', 4, 4],
        ],
      ),
    ],
    'SELECT query_name, ROUND(AVG(1.0 * rating / position), 2) AS quality,\n  ROUND(100.0 * AVG(CASE WHEN rating < 3 THEN 1.0 ELSE 0.0 END), 2) AS poor_query_percentage\nFROM Queries\nGROUP BY query_name;',
    [
      ['SQL', 3, 50],
      ['Web', 1.5, 0],
    ],
    'La calidad es una media de cocientes, no el cociente de dos medias.',
  ),
  p(
    1193,
    'Transacciones mensuales',
    'monthly-transactions-i',
    'Medium',
    'GROUP BY · CASE',
    'Por **month** (YYYY-MM) y country calcula trans_count, approved_count, trans_total_amount y approved_total_amount. Los dos últimos campos suman importes.',
    [
      table(
        'Transactions',
        'id INTEGER PRIMARY KEY, country TEXT, state TEXT, amount INTEGER, trans_date TEXT',
        [
          [1, 'ES', 'approved', 100, '2020-01-01'],
          [2, 'ES', 'declined', 50, '2020-01-02'],
          [3, null, 'approved', 30, '2020-01-03'],
          [4, 'ES', 'declined', 20, '2020-02-01'],
        ],
      ),
    ],
    "SELECT strftime('%Y-%m', trans_date) AS month, country, COUNT(*) AS trans_count,\n  SUM(CASE WHEN state = 'approved' THEN 1 ELSE 0 END) AS approved_count,\n  SUM(amount) AS trans_total_amount,\n  SUM(CASE WHEN state = 'approved' THEN amount ELSE 0 END) AS approved_total_amount\nFROM Transactions\nGROUP BY strftime('%Y-%m', trans_date), country;",
    [
      ['2020-01', null, 1, 1, 30, 30],
      ['2020-01', 'ES', 2, 1, 150, 100],
      ['2020-02', 'ES', 1, 0, 20, 0],
    ],
    'Agrupa por año y mes juntos para no mezclar años diferentes.',
  ),
  p(
    1174,
    'Primeros pedidos inmediatos',
    'immediate-food-delivery-ii',
    'Medium',
    'CTE · MIN',
    'Calcula **immediate_percentage** entre los primeros pedidos de cada cliente. Un pedido es inmediato si order_date coincide con customer_pref_delivery_date. Redondea a dos decimales.',
    [
      table(
        'Delivery',
        'delivery_id INTEGER PRIMARY KEY, customer_id INTEGER, order_date TEXT, customer_pref_delivery_date TEXT',
        [
          [1, 1, '2020-01-01', '2020-01-02'],
          [2, 1, '2020-01-03', '2020-01-03'],
          [3, 2, '2020-01-02', '2020-01-02'],
          [4, 3, '2020-01-04', '2020-01-04'],
        ],
      ),
    ],
    'WITH first_orders AS (\n  SELECT customer_id, MIN(order_date) AS first_day FROM Delivery GROUP BY customer_id\n)\nSELECT ROUND(100.0 * AVG(CASE WHEN d.order_date = d.customer_pref_delivery_date THEN 1.0 ELSE 0.0 END), 2) AS immediate_percentage\nFROM first_orders AS f\nJOIN Delivery AS d ON d.customer_id = f.customer_id AND d.order_date = f.first_day;',
    [[66.67]],
    'Filtra al primer pedido antes de calcular el porcentaje.',
  ),
  p(
    2356,
    'Asignaturas distintas por docente',
    'number-of-unique-subjects-taught-by-each-teacher',
    'Easy',
    'COUNT DISTINCT',
    'Devuelve teacher_id y **cnt**, el número de asignaturas distintas impartidas por cada docente, aunque las imparta en varios departamentos.',
    [
      table(
        'Teacher',
        'teacher_id INTEGER, subject_id INTEGER, dept_id INTEGER',
        [
          [1, 10, 1],
          [1, 10, 2],
          [1, 20, 1],
          [2, 10, 1],
        ],
      ),
    ],
    'SELECT teacher_id, COUNT(DISTINCT subject_id) AS cnt\nFROM Teacher\nGROUP BY teacher_id;',
    [
      [1, 2],
      [2, 1],
    ],
    'Cuenta subject_id distintos, no combinaciones con dept_id.',
  ),
  p(
    1141,
    'Usuarios activos en treinta días',
    'user-activity-for-the-past-30-days-i',
    'Easy',
    'fechas · COUNT DISTINCT',
    'Para los 30 días que terminan el **2019-07-27**, incluido ese día, devuelve day y active_users distintos por fecha. Omite los días sin actividad.',
    [
      table(
        'Activity',
        'user_id INTEGER, session_id INTEGER, activity_date TEXT, activity_type TEXT',
        [
          [1, 1, '2019-06-27', 'open_session'],
          [1, 2, '2019-06-28', 'open_session'],
          [1, 2, '2019-06-28', 'end_session'],
          [2, 3, '2019-06-28', 'open_session'],
          [1, 4, '2019-07-27', 'open_session'],
          [3, 5, '2019-07-28', 'open_session'],
        ],
      ),
    ],
    "SELECT activity_date AS day, COUNT(DISTINCT user_id) AS active_users\nFROM Activity\nWHERE activity_date BETWEEN date('2019-07-27', '-29 day') AND '2019-07-27'\nGROUP BY activity_date;",
    [
      ['2019-06-28', 2],
      ['2019-07-27', 1],
    ],
    'El intervalo inclusivo empieza 29 días antes; un usuario cuenta una vez por día.',
  ),
  p(
    1070,
    'Ventas del primer año',
    'product-sales-analysis-iii',
    'Medium',
    'CTE · JOIN',
    'Devuelve **product_id, first_year, quantity y price** de cada venta realizada en el primer año en que se vendió su producto. Conserva todas las ventas de ese año.',
    [
      table(
        'Sales',
        'sale_id INTEGER, product_id INTEGER, year INTEGER, quantity INTEGER, price INTEGER',
        [
          [1, 10, 2019, 2, 50],
          [2, 10, 2019, 3, 55],
          [3, 10, 2020, 4, 60],
          [4, 20, 2021, 1, 80],
        ],
      ),
    ],
    'WITH first_sales AS (SELECT product_id, MIN(year) AS first_year FROM Sales GROUP BY product_id)\nSELECT s.product_id, f.first_year, s.quantity, s.price\nFROM Sales AS s\nJOIN first_sales AS f ON f.product_id = s.product_id AND f.first_year = s.year;',
    [
      [10, 2019, 2, 50],
      [10, 2019, 3, 55],
      [20, 2021, 1, 80],
    ],
    'MIN localiza el año; el JOIN recupera todas sus ventas, no una fila arbitraria.',
  ),
  p(
    596,
    'Clases con al menos cinco alumnos',
    'classes-with-at-least-5-students',
    'Easy',
    'HAVING',
    'Devuelve **class** de las clases con al menos cinco estudiantes inscritos.',
    [
      table('Courses', 'student TEXT, class TEXT', [
        ['A', 'SQL'],
        ['B', 'SQL'],
        ['C', 'SQL'],
        ['D', 'SQL'],
        ['E', 'SQL'],
        ['A', 'Web'],
        ['B', 'Web'],
      ]),
    ],
    'SELECT class\nFROM Courses\nGROUP BY class\nHAVING COUNT(*) >= 5;',
    [['SQL']],
    'HAVING aplica el umbral a cada grupo ya contado.',
  ),
  p(
    1729,
    'Número de seguidores',
    'find-followers-count',
    'Easy',
    'COUNT · ORDER BY',
    'Devuelve user_id y **followers_count** de cada usuario presente en Followers, ordenados por user_id.',
    [
      table('Followers', 'user_id INTEGER, follower_id INTEGER', [
        [2, 1],
        [1, 3],
        [2, 3],
        [2, 4],
      ]),
    ],
    'SELECT user_id, COUNT(*) AS followers_count\nFROM Followers\nGROUP BY user_id\nORDER BY user_id;',
    [
      [1, 1],
      [2, 3],
    ],
    'Cada pareja usuario-seguidor representa un seguidor.',
  ),
  p(
    619,
    'Mayor número no repetido',
    'biggest-single-number',
    'Easy',
    'HAVING · MAX',
    'Devuelve como **num** el mayor número que aparece exactamente una vez. Si no existe ninguno, devuelve una fila con NULL.',
    [table('MyNumbers', 'num INTEGER', [[8], [8], [3], [5], [2], [2]])],
    'WITH singles AS (SELECT num FROM MyNumbers GROUP BY num HAVING COUNT(*) = 1)\nSELECT MAX(num) AS num FROM singles;',
    [[5]],
    'MAX sobre un conjunto vacío devuelve NULL, pero sigue produciendo una fila.',
  ),
  p(
    1045,
    'Clientes que compraron todos los productos',
    'customers-who-bought-all-products',
    'Medium',
    'COUNT DISTINCT · HAVING',
    'Devuelve customer_id de quienes compraron todos los product_key de Product. Las compras repetidas no cuentan como productos nuevos.',
    [
      table('Customer', 'customer_id INTEGER, product_key INTEGER', [
        [1, 10],
        [1, 20],
        [1, 10],
        [2, 10],
        [3, 10],
        [3, 20],
      ]),
      table('Product', 'product_key INTEGER PRIMARY KEY', [[10], [20]]),
    ],
    'WITH total AS (SELECT COUNT(*) AS products_count FROM Product)\nSELECT c.customer_id\nFROM Customer AS c CROSS JOIN total AS t\nGROUP BY c.customer_id, t.products_count\nHAVING COUNT(DISTINCT c.product_key) = t.products_count;',
    [[1], [3]],
    'Compara el número de productos distintos comprados con el tamaño del catálogo.',
  ),
  p(
    1731,
    'Resumen de reportes por responsable',
    'the-number-of-employees-which-report-to-each-employee',
    'Easy',
    'SELF JOIN · AVG',
    'Para cada empleado con reportes directos devuelve **employee_id, name, reports_count y average_age**. Redondea la edad media al entero más cercano y ordena por employee_id.',
    [
      table(
        'Employees',
        'employee_id INTEGER PRIMARY KEY, name TEXT, reports_to INTEGER, age INTEGER',
        [
          [1, 'Ada', null, 45],
          [2, 'Ben', 1, 30],
          [3, 'Cora', 1, 31],
          [4, 'Dan', 2, 22],
        ],
      ),
    ],
    'SELECT m.employee_id, m.name, COUNT(*) AS reports_count, ROUND(AVG(e.age), 0) AS average_age\nFROM Employees AS m JOIN Employees AS e ON e.reports_to = m.employee_id\nGROUP BY m.employee_id, m.name\nORDER BY m.employee_id;',
    [
      [1, 'Ada', 2, 31],
      [2, 'Ben', 1, 22],
    ],
    'El JOIN solo reúne reportes directos; no recorre toda la jerarquía.',
  ),
  p(
    1789,
    'Departamento principal de cada empleado',
    'primary-department-for-each-employee',
    'Easy',
    'CTE · COUNT',
    'Devuelve employee_id y department_id del departamento marcado con primary_flag Y. Para empleados de un único departamento, devuelve ese departamento aunque tenga N.',
    [
      table(
        'Employee',
        'employee_id INTEGER, department_id INTEGER, primary_flag TEXT',
        [
          [1, 10, 'N'],
          [2, 10, 'N'],
          [2, 20, 'Y'],
          [3, 30, 'N'],
        ],
      ),
    ],
    "WITH counts AS (SELECT employee_id, COUNT(*) AS departments FROM Employee GROUP BY employee_id)\nSELECT e.employee_id, e.department_id\nFROM Employee AS e JOIN counts AS c ON c.employee_id = e.employee_id\nWHERE e.primary_flag = 'Y' OR c.departments = 1;",
    [
      [1, 10],
      [2, 20],
      [3, 30],
    ],
    'Cuenta las asignaciones antes de elegir el departamento principal.',
  ),
  p(
    610,
    '¿Se puede formar un triángulo?',
    'triangle-judgement',
    'Easy',
    'CASE',
    'Para cada terna x, y, z añade **triangle** con Yes si sus longitudes forman un triángulo y No en caso contrario.',
    [
      table('Triangle', 'x INTEGER, y INTEGER, z INTEGER', [
        [3, 4, 5],
        [1, 2, 3],
        [10, 2, 3],
      ]),
    ],
    "SELECT x, y, z, CASE WHEN x + y > z AND x + z > y AND y + z > x THEN 'Yes' ELSE 'No' END AS triangle\nFROM Triangle;",
    [
      [3, 4, 5, 'Yes'],
      [1, 2, 3, 'No'],
      [10, 2, 3, 'No'],
    ],
    'Las tres desigualdades deben ser estrictas: una figura plana no es un triángulo.',
  ),
  p(
    180,
    'Tres números consecutivos iguales',
    'consecutive-numbers',
    'Medium',
    'SELF JOIN · DISTINCT',
    'Devuelve sin duplicados **ConsecutiveNums**: números que aparecen en al menos tres registros con id consecutivos.',
    [
      table('Logs', 'id INTEGER PRIMARY KEY, num TEXT', [
        [1, '7'],
        [2, '7'],
        [3, '7'],
        [4, '7'],
        [5, '2'],
        [6, '2'],
        [7, '3'],
      ]),
    ],
    'SELECT DISTINCT a.num AS ConsecutiveNums\nFROM Logs AS a\nJOIN Logs AS b ON b.id = a.id + 1\nJOIN Logs AS c ON c.id = a.id + 2\nWHERE a.num = b.num AND b.num = c.num;',
    [['7']],
    'Tres alias permiten comparar cada registro con sus dos siguientes.',
  ),
  p(
    1164,
    'Precio de los productos en una fecha',
    'product-price-at-a-given-date',
    'Medium',
    'CTE · LEFT JOIN',
    'Devuelve product_id y **price** vigente el **2019-08-16**. Antes del primer cambio, todo producto cuesta 10.',
    [
      table(
        'Products',
        'product_id INTEGER, new_price INTEGER, change_date TEXT',
        [
          [1, 20, '2019-08-14'],
          [1, 35, '2019-08-16'],
          [2, 50, '2019-08-14'],
          [2, 65, '2019-08-17'],
          [3, 30, '2019-08-18'],
        ],
      ),
    ],
    "WITH ids AS (SELECT DISTINCT product_id FROM Products),\nlatest AS (SELECT product_id, MAX(change_date) AS last_day FROM Products WHERE change_date <= '2019-08-16' GROUP BY product_id)\nSELECT i.product_id, COALESCE(p.new_price, 10) AS price\nFROM ids AS i\nLEFT JOIN latest AS l ON l.product_id = i.product_id\nLEFT JOIN Products AS p ON p.product_id = l.product_id AND p.change_date = l.last_day;",
    [
      [1, 35],
      [2, 50],
      [3, 10],
    ],
    'Parte de todos los productos y busca el último cambio no posterior a la fecha.',
  ),
  p(
    1204,
    'Última persona que cabe en el autobús',
    'last-person-to-fit-in-the-bus',
    'Medium',
    'SELF JOIN · acumulado',
    'Las personas suben por turn ascendente. Devuelve **person_name** de la última que puede subir sin superar **1000 kg acumulados**.',
    [
      table(
        'Queue',
        'person_id INTEGER PRIMARY KEY, person_name TEXT, weight INTEGER, turn INTEGER',
        [
          [1, 'Ada', 250, 1],
          [2, 'Ben', 350, 2],
          [3, 'Cora', 400, 3],
          [4, 'Dan', 100, 4],
        ],
      ),
    ],
    'SELECT q.person_name\nFROM Queue AS q JOIN Queue AS prior ON prior.turn <= q.turn\nGROUP BY q.person_id, q.person_name, q.turn\nHAVING SUM(prior.weight) <= 1000\nORDER BY q.turn DESC\nLIMIT 1;',
    [['Cora']],
    'Suma el peso de cada persona junto con el de quienes la preceden.',
  ),
  p(
    1907,
    'Cuentas por categoría salarial',
    'count-salary-categories',
    'Medium',
    'UNION ALL · COUNT',
    'Devuelve category y accounts_count para **Low Salary** (<20000), **Average Salary** (20000–50000 inclusive) y **High Salary** (>50000). Deben aparecer las tres, incluso con cero cuentas.',
    [
      table('Accounts', 'account_id INTEGER PRIMARY KEY, income INTEGER', [
        [1, 10000],
        [2, 60000],
        [3, 80000],
      ]),
    ],
    "SELECT 'Low Salary' AS category, COUNT(*) AS accounts_count FROM Accounts WHERE income < 20000\nUNION ALL\nSELECT 'Average Salary', COUNT(*) FROM Accounts WHERE income BETWEEN 20000 AND 50000\nUNION ALL\nSELECT 'High Salary', COUNT(*) FROM Accounts WHERE income > 50000;",
    [
      ['Low Salary', 1],
      ['Average Salary', 0],
      ['High Salary', 2],
    ],
    'Cada COUNT devuelve una fila aunque su filtro no encuentre cuentas.',
  ),
  p(
    1978,
    'Empleados cuyo responsable se marchó',
    'employees-whose-manager-left-the-company',
    'Easy',
    'LEFT JOIN · ausencia',
    'Devuelve employee_id de empleados con salario **menor que 30000** cuyo manager_id ya no existe en Employees. No incluyas a quienes nunca tuvieron responsable. Ordena por employee_id.',
    [
      table(
        'Employees',
        'employee_id INTEGER PRIMARY KEY, name TEXT, manager_id INTEGER, salary INTEGER',
        [
          [1, 'Ada', null, 25000],
          [2, 'Ben', 9, 20000],
          [3, 'Cora', 1, 22000],
          [4, 'Dan', 9, 30000],
        ],
      ),
    ],
    'SELECT e.employee_id\nFROM Employees AS e LEFT JOIN Employees AS m ON m.employee_id = e.manager_id\nWHERE e.salary < 30000 AND e.manager_id IS NOT NULL AND m.employee_id IS NULL\nORDER BY e.employee_id;',
    [[2]],
    'Distingue un manager_id ausente de una referencia a un responsable que ya no existe.',
  ),
  p(
    626,
    'Intercambiar asientos',
    'exchange-seats',
    'Medium',
    'CASE · LEFT JOIN',
    'Intercambia los estudiantes de cada pareja de asientos consecutivos (1 con 2, 3 con 4…). Si queda un último asiento impar, conserva su estudiante. Devuelve **id y student** por id ascendente.',
    [
      table('Seat', 'id INTEGER PRIMARY KEY, student TEXT', [
        [1, 'Ada'],
        [2, 'Ben'],
        [3, 'Cora'],
        [4, 'Dan'],
        [5, 'Eva'],
      ]),
    ],
    'SELECT s.id, COALESCE(partner.student, s.student) AS student\nFROM Seat AS s\nLEFT JOIN Seat AS partner ON partner.id = CASE WHEN s.id % 2 = 1 THEN s.id + 1 ELSE s.id - 1 END\nORDER BY s.id;',
    [
      [1, 'Ben'],
      [2, 'Ada'],
      [3, 'Dan'],
      [4, 'Cora'],
      [5, 'Eva'],
    ],
    'Busca el asiento compañero y conserva el estudiante original cuando no exista.',
  ),
  p(
    1341,
    'Usuario y película destacados',
    'movie-rating',
    'Medium',
    'CTE · UNION ALL',
    'Devuelve dos filas en **results**: primero el usuario que valoró más películas; después la película con mayor valoración media en febrero de 2020. En ambos empates elige el nombre alfabéticamente menor.',
    [
      table('Movies', 'movie_id INTEGER PRIMARY KEY, title TEXT', [
        [1, 'Alba'],
        [2, 'Brisa'],
      ]),
      table('Users', 'user_id INTEGER PRIMARY KEY, name TEXT', [
        [1, 'Ada'],
        [2, 'Ben'],
      ]),
      table(
        'MovieRating',
        'movie_id INTEGER, user_id INTEGER, rating INTEGER, created_at TEXT',
        [
          [1, 1, 4, '2020-02-01'],
          [2, 1, 5, '2020-02-03'],
          [1, 2, 4, '2020-02-04'],
          [2, 2, 3, '2020-03-01'],
        ],
      ),
    ],
    "WITH top_user AS (\n  SELECT u.name AS results FROM Users AS u JOIN MovieRating AS r ON r.user_id = u.user_id\n  GROUP BY u.user_id, u.name ORDER BY COUNT(*) DESC, u.name LIMIT 1\n), top_movie AS (\n  SELECT m.title AS results FROM Movies AS m JOIN MovieRating AS r ON r.movie_id = m.movie_id\n  WHERE r.created_at >= '2020-02-01' AND r.created_at < '2020-03-01'\n  GROUP BY m.movie_id, m.title ORDER BY AVG(r.rating) DESC, m.title LIMIT 1\n)\nSELECT results FROM top_user\nUNION ALL\nSELECT results FROM top_movie;",
    [['Ada'], ['Brisa']],
    'Las dos clasificaciones usan poblaciones diferentes; UNION ALL conserva las dos respuestas aunque el texto coincida.',
  ),
  p(
    1321,
    'Crecimiento del restaurante',
    'restaurant-growth',
    'Medium',
    'CTE · ventana de fechas',
    'Para cada día con siete días completos disponibles, devuelve **visited_on, amount y average_amount** de ese día y los seis anteriores. Suma primero todos los clientes de cada día, redondea la media a dos decimales y ordena por fecha. Hay actividad todos los días.',
    [
      table(
        'Customer',
        'customer_id INTEGER, name TEXT, visited_on TEXT, amount INTEGER',
        [
          [1, 'Ada', '2020-01-01', 10],
          [2, 'Ben', '2020-01-02', 20],
          [3, 'Cora', '2020-01-03', 30],
          [4, 'Dan', '2020-01-04', 40],
          [5, 'Eva', '2020-01-05', 50],
          [6, 'Fay', '2020-01-06', 60],
          [7, 'Gil', '2020-01-07', 30],
          [8, 'Hal', '2020-01-07', 40],
          [1, 'Ada', '2020-01-08', 80],
        ],
      ),
    ],
    "WITH daily AS (SELECT visited_on, SUM(amount) AS total FROM Customer GROUP BY visited_on)\nSELECT d.visited_on, SUM(p.total) AS amount, ROUND(AVG(p.total), 2) AS average_amount\nFROM daily AS d\nJOIN daily AS p ON p.visited_on BETWEEN date(d.visited_on, '-6 day') AND d.visited_on\nGROUP BY d.visited_on\nHAVING COUNT(*) = 7\nORDER BY d.visited_on;",
    [
      ['2020-01-07', 280, 40],
      ['2020-01-08', 350, 50],
    ],
    'Agrupar por fecha evita que dos clientes del mismo día alteren el tamaño de la ventana.',
  ),
  p(
    602,
    'La persona con más amigos',
    'friend-requests-ii-who-has-the-most-friends',
    'Medium',
    'UNION ALL · GROUP BY',
    'Cada solicitud aceptada crea una amistad en ambos sentidos. Devuelve **id y num** de la persona con más amigos. El ejercicio garantiza un único máximo.',
    [
      table(
        'RequestAccepted',
        'requester_id INTEGER, accepter_id INTEGER, accept_date TEXT',
        [
          [1, 2, '2020-01-01'],
          [1, 3, '2020-01-02'],
          [2, 3, '2020-01-03'],
          [3, 4, '2020-01-04'],
        ],
      ),
    ],
    'WITH endpoints AS (\n  SELECT requester_id AS id FROM RequestAccepted\n  UNION ALL\n  SELECT accepter_id AS id FROM RequestAccepted\n)\nSELECT id, COUNT(*) AS num FROM endpoints\nGROUP BY id ORDER BY num DESC LIMIT 1;',
    [[3, 3]],
    'Cuenta cada extremo de cada amistad, no solo a quien envió la solicitud.',
  ),
  p(
    585,
    'Inversiones de 2016',
    'investments-in-2016',
    'Medium',
    'CTE · HAVING',
    'Suma **tiv_2016**, con dos decimales, de las pólizas cuyo tiv_2015 coincide con el de otra póliza y cuya pareja (lat, lon) no coincide con ninguna otra.',
    [
      table(
        'Insurance',
        'pid INTEGER PRIMARY KEY, tiv_2015 REAL, tiv_2016 REAL, lat REAL, lon REAL',
        [
          [1, 10, 5, 1, 1],
          [2, 10, 15, 2, 2],
          [3, 20, 30, 3, 3],
          [4, 20, 40, 3, 3],
          [5, 30, 50, 4, 4],
        ],
      ),
    ],
    'WITH repeated AS (SELECT tiv_2015 FROM Insurance GROUP BY tiv_2015 HAVING COUNT(*) > 1),\nunique_places AS (SELECT lat, lon FROM Insurance GROUP BY lat, lon HAVING COUNT(*) = 1)\nSELECT ROUND(SUM(i.tiv_2016), 2) AS tiv_2016\nFROM Insurance AS i\nJOIN repeated AS r ON r.tiv_2015 = i.tiv_2015\nJOIN unique_places AS u ON u.lat = i.lat AND u.lon = i.lon;',
    [[20]],
    'Comprueba la unicidad de la pareja de coordenadas, no de cada coordenada por separado.',
  ),
  p(
    1667,
    'Normalizar nombres',
    'fix-names-in-a-table',
    'Easy',
    'UPPER · LOWER',
    'Devuelve user_id y **name** con la primera letra en mayúscula y el resto en minúsculas, ordenados por user_id. Los nombres del ejercicio usan letras inglesas.',
    [
      table('Users', 'user_id INTEGER PRIMARY KEY, name TEXT', [
        [2, 'aDA'],
        [1, 'bEN'],
        [3, 'X'],
      ]),
    ],
    'SELECT user_id, UPPER(SUBSTR(name, 1, 1)) || LOWER(SUBSTR(name, 2)) AS name\nFROM Users ORDER BY user_id;',
    [
      [1, 'Ben'],
      [2, 'Ada'],
      [3, 'X'],
    ],
    'SUBSTR separa la primera letra; || concatena texto en SQLite.',
  ),
  p(
    1527,
    'Pacientes con diabetes tipo I',
    'patients-with-a-condition',
    'Easy',
    'texto · LIKE',
    'Devuelve patient_id, patient_name y conditions de pacientes con algún código que **empiece por DIAB1**. Los códigos están separados por espacios: el prefijo debe comenzar al inicio del texto o después de un espacio.',
    [
      table(
        'Patients',
        'patient_id INTEGER PRIMARY KEY, patient_name TEXT, conditions TEXT',
        [
          [1, 'Ada', 'DIAB100'],
          [2, 'Ben', 'ASTH DIAB12'],
          [3, 'Cora', 'XDIAB1'],
          [4, 'Dan', ''],
          [5, 'Eva', 'DIAB2'],
        ],
      ),
    ],
    "SELECT patient_id, patient_name, conditions\nFROM Patients\nWHERE conditions LIKE 'DIAB1%' OR conditions LIKE '% DIAB1%';",
    [
      [1, 'Ada', 'DIAB100'],
      [2, 'Ben', 'ASTH DIAB12'],
    ],
    'Buscar %DIAB1% sin límite izquierdo incluiría códigos incorrectos como XDIAB1.',
  ),
  {
    ...p(
      196,
      'Eliminar correos duplicados',
      'delete-duplicate-emails',
      'Easy',
      'DELETE · subconsulta',
      'Elimina los correos repetidos de Person y conserva, para cada email, la fila con **menor id**. Escribe un DELETE; el resultado es la tabla Person después del borrado. Cada ejecución trabaja en una copia temporal de los datos iniciales.',
      [
        table('Person', 'id INTEGER PRIMARY KEY, email TEXT', [
          [1, 'ada@example.com'],
          [2, 'ben@example.com'],
          [3, 'ada@example.com'],
          [4, 'ben@example.com'],
          [5, 'cora@example.com'],
        ]),
      ],
      'DELETE FROM Person\nWHERE id NOT IN (SELECT MIN(id) FROM Person GROUP BY email);',
      [
        [1, 'ada@example.com'],
        [2, 'ben@example.com'],
        [5, 'cora@example.com'],
      ],
      'La subconsulta identifica los id que deben conservarse; DELETE elimina los demás.',
    ),
    mode: 'delete',
    resultTable: 'Person',
  },
  p(
    176,
    'Segundo salario más alto',
    'second-highest-salary',
    'Medium',
    'DENSE_RANK · MAX',
    'Devuelve el segundo salario **distinto** más alto como SecondHighestSalary. Si no hay dos salarios distintos, devuelve una fila con NULL.',
    [
      table('Employee', 'id INTEGER PRIMARY KEY, salary INTEGER', [
        [1, 300],
        [2, 300],
        [3, 200],
        [4, 100],
      ]),
    ],
    'WITH ranked AS (\n  SELECT salary, DENSE_RANK() OVER (PARTITION BY 1 ORDER BY salary DESC) AS salary_rank FROM Employee\n)\nSELECT MAX(salary) AS SecondHighestSalary FROM ranked WHERE salary_rank = 2;',
    [[200]],
    'DENSE_RANK no deja huecos por empates y MAX conserva una fila incluso si falta el segundo puesto.',
  ),
  p(
    1484,
    'Productos vendidos por fecha',
    'group-sold-products-by-the-date',
    'Easy',
    'DISTINCT · GROUP_CONCAT',
    'Para cada sell_date devuelve **num_sold**, el número de productos distintos, y **products**, sus nombres únicos separados por comas y ordenados alfabéticamente. Ordena las filas por fecha.',
    [
      table('Activities', 'sell_date TEXT, product TEXT', [
        ['2020-01-01', 'Mouse'],
        ['2020-01-01', 'Cable'],
        ['2020-01-01', 'Mouse'],
        ['2020-01-02', 'Monitor'],
      ]),
    ],
    'WITH unique_products AS (SELECT DISTINCT sell_date, product FROM Activities),\nlisted AS (\n  SELECT sell_date,\n    GROUP_CONCAT(product) OVER (PARTITION BY sell_date ORDER BY product) AS products,\n    COUNT(*) OVER (PARTITION BY sell_date ORDER BY product) AS num_sold\n  FROM unique_products\n), totals AS (SELECT sell_date, COUNT(*) AS total FROM unique_products GROUP BY sell_date)\nSELECT l.sell_date, l.num_sold, l.products\nFROM listed AS l JOIN totals AS t ON t.sell_date = l.sell_date AND t.total = l.num_sold\nORDER BY l.sell_date;',
    [
      ['2020-01-01', 2, 'Cable,Mouse'],
      ['2020-01-02', 1, 'Monitor'],
    ],
    'Elimina duplicados primero. La ventana concatena en orden; el JOIN conserva la fila que ya contiene todos los productos del día.',
  ),
  p(
    1327,
    'Productos pedidos en febrero',
    'list-the-products-ordered-in-a-period',
    'Easy',
    'JOIN · fechas · HAVING',
    'Devuelve **product_name y unit** de productos con al menos 100 unidades pedidas durante febrero de 2020.',
    [
      table(
        'Products',
        'product_id INTEGER PRIMARY KEY, product_name TEXT, product_category TEXT',
        [
          [1, 'Cable', 'Tech'],
          [2, 'Libro', 'Books'],
          [3, 'Mouse', 'Tech'],
        ],
      ),
      table('Orders', 'product_id INTEGER, order_date TEXT, unit INTEGER', [
        [1, '2020-02-01', 60],
        [1, '2020-02-29', 40],
        [2, '2020-02-10', 99],
        [3, '2020-03-01', 200],
      ]),
    ],
    "SELECT p.product_name, SUM(o.unit) AS unit\nFROM Products AS p JOIN Orders AS o ON o.product_id = p.product_id\nWHERE o.order_date >= '2020-02-01' AND o.order_date < '2020-03-01'\nGROUP BY p.product_id, p.product_name\nHAVING SUM(o.unit) >= 100;",
    [['Cable', 100]],
    'El límite superior exclusivo incluye todo febrero, también el día 29.',
  ),
  p(
    1517,
    'Usuarios con correos válidos',
    'find-users-with-valid-e-mails',
    'Easy',
    'REGEXP',
    'Devuelve user_id, name y mail de usuarios cuyo correo empieza por una letra inglesa, sigue con letras, dígitos, punto, guion o guion bajo, y termina exactamente en **@leetcode.com**, en minúsculas.',
    [
      table('Users', 'user_id INTEGER PRIMARY KEY, name TEXT, mail TEXT', [
        [1, 'Ada', 'ada@leetcode.com'],
        [2, 'Ben', 'b.en-2@leetcode.com'],
        [3, 'Cora', '.cora@leetcode.com'],
        [4, 'Dan', 'dan@LeetCode.com'],
        [5, 'Eva', 'eva#1@leetcode.com'],
        [6, 'Fay', 'fay@leetcode.com.extra'],
      ]),
    ],
    "SELECT user_id, name, mail\nFROM Users\nWHERE REGEXP('^[A-Za-z][A-Za-z0-9_.-]*@leetcode[.]com$', mail);",
    [
      [1, 'Ada', 'ada@leetcode.com'],
      [2, 'Ben', 'b.en-2@leetcode.com'],
    ],
    'REGEXP está registrada como función en este SQLite local. Los anclajes exigen que coincida todo el correo.',
  ),
];
export default exercises;
